apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: php
    spec:
      containers:
      - env:
        - name: DRUPAL_VERSION
          value: "8"
        - name: PHP_FPM_ENV_VARS
          value: '["APP_ROOT","CONF_DIR","FILES_DIR","HTTP_ROOT","WODBY_APP_DOCROOT","WODBY_APP_NAME","WODBY_APP_ID","WODBY_ENVIRONMENT_NAME","WODBY_ENVIRONMENT_TYPE","WODBY_HOSTS","WODBY_HOST_PRIMARY","WODBY_URL_PRIMARY"]'
        image: wodby/drupal
        imagePullPolicy: Always
        name: php
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - make
            - check-ready
            - -f
            - /usr/local/bin/actions.mk
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          exec:
            command:
            - make
            - check-ready
            - -f
            - /usr/local/bin/actions.mk
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3        
        resources:
          requests:
            memory: 32Mi
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
      terminationGracePeriodSeconds: 30
