name: drupal8-php
type: service
title: PHP (Drupal 8)
hostname: php
labels:
- php
- php-fpm
- drupal
- drupal8
deployment:
- type: git
options:
- version: 7.4
- version: 7.3
  stability_tag: 4.13.12
  default: true
  deployment:
  - type: image
    title: Vanilla Drupal
    image: wodby/drupal:8-7.3-4.16.4
- version: 7.0
  stability_tag: 4.13.12
  eol: '2018-12-31'
# scalable is false by default.
scalable: true
containers:
- name: php
  # if main not specified the first port becomes main.
  main: true
  env:
  # remapping of existing env var.
  - name: 'PHP_NEWRELIC_LICENSE'
    value: '{{env.NEWRELIC_LICENSE}}'
  - name: PHP_NEWRELIC_APPNAME
    value: '{{wodby_app_name}}'
  # will be available.
  # - name: VARNISH_ADMIN_PORT
  ports:
  - name: fpm
    number: 9000
    # if missing, the first port of the main container considered as main.
    main: true
    type: tcp

services:
- name: ssh
  title: SSH
  command: sudo /usr/sbin/sshd -De
  ssh: true
  env:
  - name: TEST_SSH
    value: val123

links:
- name: db
  title: DBMS
  required: true
  selectors:
  - type: db
    labels:
    - mariadb
  - type: db
    labels:
    - postgres
- name: cache-storage
  title: Cache storage
  selectors:
  - type: db
    labels:
    - redis
  - type: cache-storage
    labels:
    - memcached    
- name: varnish
  title: Varnish
  selectors:
  - type: reverse-proxy
    labels:
    - varnish

storage:
- name: files
  title: Files storage
  type: shared
  size: 10

integrations:
- name: backup-destination
  title: Backups destination
  type: s3-compat
  required: false
  jobsOnly: true

jobs:
- name: backup-files # A part of k8s job name.
  title: Backup files # For listings.
  type: backup
  command: ["make", "backup"]
  integrations:
  - backup-destination
  params:
  - name: storageSizeFrom
    value: files
- name: restore-files
  type: restore
  title: Restore files
  command: ["make", "restore"]
  integrations:
  - backup-destination
  params:
  - name: storageSizeFrom
    value: files
- name: post-deployment-1
  title: my post deployment action 1
  type: post-deployment
  params:
  - name: custom-param
    value: '{{token}}'
- name: post-deployment-2 # Will be executed after post-deployment-1.
  type: pre-deployment
  title: my post deployment action 2
- name: custom-action-1
  title: My action 1
  type: custom
  command: ["make", "some", "action"]
- name: drush9-alias
  title: Download Drush 9 alias
  type: file
  command: ["make", "drush-alias"]
